name: Allowlist Request
description: Report incorrectly blocked domain(s).
labels: ["allow"]
assignees: 
  - hagezi
body:
  - type: dropdown
    id: adblocker
    attributes:
      label: Which AdBlocker/DNS cloud service do you use?
      description: |
        Select the AdBlocker/DNS cloud service you are using. If it's not listed, select "Other" and provide its name in the comments below.
      multiple: true
      options:
        - AdGuard
        - AdGuard DNS
        - AdGuard Home
        - Pi-hole
        - uBlock Origin
        - adblock-lean
        - ControlD
        - DNSwarden
        - NextDNS
        - RethinkDNS
        - Other
    validations:
      required: true
  
  - type: input
    id: other
    attributes:
      label: If "Other" selected, provide the name here.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: ControlD users
      description: |
        For ControlD users: Ensure the "Block Response" in the profile settings is not set to "Custom" or "Branded." This helps avoid false positives.
      options:
        - label: I confirm the "Block Response" is not set to "Custom" or "Branded," and the issue persists.
          required: false

  - type: checkboxes
    attributes:
      label: NextDNS users
      description: |
        For NextDNS users: Ensure the block page is disabled in the settings to avoid conflicts.
      options:
        - label: I confirm the block page is disabled, and the issue persists.
          required: false

  - type: dropdown
    id: blocklists
    attributes:
      label: Which Hagezi blocklist(s) caused the issue?
      multiple: true
      options:
        - Multi LIGHT
        - Multi NORMAL
        - Multi PRO
        - Multi PRO mini
        - Multi PRO++
        - Multi PRO++ mini
        - Multi ULTIMATE
        - Multi ULTIMATE mini
        - Fake
        - Pop-Up Ads
        - Threat Intelligence Feeds
        - Threat Intelligence Feeds medium
        - Threat Intelligence Feeds IPs
        - DoH/VPN/TOR/Proxy Bypass
        - DoH Bypass
        - DoH Bypass IPs
        - Safesearch not supported
        - Dynamic DNS
        - Badware Hoster
        - Most Abused TLDs
        - Anti Piracy
        - Gambling
        - Native Tracker
        - Allowlist Referral
    validations:
      required: true

  - type: checkboxes
    id: other-blocklists
    attributes:
      label: Are you using any blocklists not from Hagezi?
      description: |
        To ensure accurate troubleshooting, confirm that you are not using blocklists from other sources.
      options:
        - label: I confirm I am not using blocklists from sources other than Hagezi.
          required: true

  - type: textarea
    id: domains
    attributes:
      label: Domain(s) to be unblocked
      description: |
        List the domains you believe are incorrectly blocked. Separate multiple domains with new line (like a list).
    validations:
      required: true
  
  - type: textarea
    id: reason
    attributes:
      label: Why should these domain(s) be unblocked?
      description: |
        Provide detailed reasoning for the allowlist request. Include steps to reproduce the issue and attach screenshots if applicable.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Privacy Confirmation
      description: |
        By submitting this issue, you confirm that no private information is included in your report.
      options:
        - label: I confirm that the report does not contain any private information.
          required: true
