name: Denylist Request
description: Report domain(s) that should be added to the denylist.
labels: ["deny"]
assignees: 
  - hagezi
body:
  - type: textarea
    id: domains
    attributes:
      label: Domain(s) to be blocked
      description: |
        Provide the domains that should be blocked. Ensure you include only pure domains (e.g., example.com). Do not include adblock rules, URLs, or other formats.
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Justification for blocking the domain(s)
      description: |
        Clearly explain why each domain should be blocked. Include details such as tracking behavior, malicious activity, or where and how the domain is accessed.
    validations:
      required: true
  
  - type: checkboxes
    id: blocked
    attributes:
      label: Confirmation
      description: |
        Confirm the following points to ensure your request is valid and avoids duplication.
      options:
        - label: I have verified that no existing issue explains why the domain(s) were previously unblocked or the blocking was declined.
          required: true
        - label: I have checked that the domain(s) are not already blocked by Hagezi's blocklists.
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Privacy Confirmation
      description: |
        By submitting this request, you confirm that the report does not contain any private or sensitive information.
      options:
        - label: I confirm that the report does not contain any private or sensitive information.
          required: true
